.build: &build
  stage: build
  only:
    - main
  script:
    - docker pull $NAMESPACE:$PHP_VERSION-node$NODE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$PHP_VERSION-node$NODE_VERSION --build-arg PHP_VERSION=$PHP_VERSION --build-arg NODE_VERSION=$NODE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$PHP_VERSION-node$NODE_VERSION -f php/Dockerfile .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker push $NAMESPACE:$PHP_VERSION-node$NODE_VERSION

variables:
  DOCKER_DRIVER: overlay2
  NAMESPACE: cstadler333/gitlab-ci-deployer

image: docker:latest
services:
  - docker:dind

Deployer PHP 7.4 Node 14:
  <<: *build
  variables:
    PHP_VERSION: "7.4"
    NODE_VERSION: "14"

Deployer PHP 7.4 Node 16:
  <<: *build
  variables:
    PHP_VERSION: "7.4"
    NODE_VERSION: "16"

Deployer PHP 7.4 Node 18:
  <<: *build
  variables:
    PHP_VERSION: "7.4"
    NODE_VERSION: "18"
  after_script:
    - docker tag $NAMESPACE:$PHP_VERSION-node$NODE_VERSION $NAMESPACE:$PHP_VERSION
    - docker push $NAMESPACE:$PHP_VERSION

Deployer PHP 8.0 Node 16:
  <<: *build
  variables:
    PHP_VERSION: "8.0"
    NODE_VERSION: "16"

Deployer PHP 8.0 Node 18:
  <<: *build
  variables:
    PHP_VERSION: "8.0"
    NODE_VERSION: "18"

Deployer PHP 8.0 Node 20:
  <<: *build
  variables:
    PHP_VERSION: "8.0"
    NODE_VERSION: "20"
  after_script:
    - docker tag $NAMESPACE:$PHP_VERSION-node$NODE_VERSION $NAMESPACE:$PHP_VERSION
    - docker push $NAMESPACE:$PHP_VERSION

Deployer PHP 8.1 Node 16:
  <<: *build
  variables:
    PHP_VERSION: "8.1"
    NODE_VERSION: "16"

Deployer PHP 8.1 Node 18:
  <<: *build
  variables:
    PHP_VERSION: "8.1"
    NODE_VERSION: "18"

Deployer PHP 8.1 Node 20:
  <<: *build
  variables:
    PHP_VERSION: "8.1"
    NODE_VERSION: "20"

Deployer PHP 8.1 Node 22:
  <<: *build
  variables:
    PHP_VERSION: "8.1"
    NODE_VERSION: "22"
  after_script:
    - docker tag $NAMESPACE:$PHP_VERSION-node$NODE_VERSION $NAMESPACE:$PHP_VERSION
    - docker push $NAMESPACE:$PHP_VERSION

Deployer PHP 8.2 Node 16:
  <<: *build
  variables:
    PHP_VERSION: "8.2"
    NODE_VERSION: "16"

Deployer PHP 8.2 Node 18:
  <<: *build
  variables:
    PHP_VERSION: "8.2"
    NODE_VERSION: "18"

Deployer PHP 8.2 Node 20:
  <<: *build
  variables:
    PHP_VERSION: "8.2"
    NODE_VERSION: "20"

Deployer PHP 8.2 Node 22:
  <<: *build
  variables:
    PHP_VERSION: "8.2"
    NODE_VERSION: "22"
  after_script:
    - docker tag $NAMESPACE:$PHP_VERSION-node$NODE_VERSION $NAMESPACE:$PHP_VERSION
    - docker push $NAMESPACE:$PHP_VERSION

Deployer PHP 8.3 Node 16:
  <<: *build
  variables:
    PHP_VERSION: "8.3"
    NODE_VERSION: "16"

Deployer PHP 8.3 Node 18:
  <<: *build
  variables:
    PHP_VERSION: "8.3"
    NODE_VERSION: "18"

Deployer PHP 8.3 Node 20:
  <<: *build
  variables:
    PHP_VERSION: "8.3"
    NODE_VERSION: "20"

Deployer PHP 8.3 Node 22:
  <<: *build
  variables:
    PHP_VERSION: "8.3"
    NODE_VERSION: "22"
  after_script:
    - docker tag $NAMESPACE:$PHP_VERSION-node$NODE_VERSION $NAMESPACE:$PHP_VERSION
    - docker push $NAMESPACE:$PHP_VERSION

Deployer PHP 8.4 Node 16:
  <<: *build
  variables:
    PHP_VERSION: "8.4"
    NODE_VERSION: "16"

Deployer PHP 8.4 Node 18:
  <<: *build
  variables:
    PHP_VERSION: "8.4"
    NODE_VERSION: "18"

Deployer PHP 8.4 Node 20:
  <<: *build
  variables:
    PHP_VERSION: "8.4"
    NODE_VERSION: "20"

Deployer PHP 8.4 Node 22:
  <<: *build
  variables:
    PHP_VERSION: "8.4"
    NODE_VERSION: "22"
  after_script:
    - docker tag $NAMESPACE:$PHP_VERSION-node$NODE_VERSION $NAMESPACE:$PHP_VERSION
    - docker push $NAMESPACE:$PHP_VERSION
    - docker tag $NAMESPACE:$PHP_VERSION-node$NODE_VERSION $NAMESPACE:latest
    - docker push $NAMESPACE:latest
