.build: &build
  stage: build
  script:
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/$IMAGE_VERSION/Dockerfile .
    - docker push $NAMESPACE:$IMAGE_VERSION

variables:
  DOCKER_DRIVER: overlay2
  NAMESPACE: cstadler333/gitlab-ci-deployer

image: docker:latest
services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

Deployer 7.4:
  <<: *build
  only:
    - main
  variables:
    IMAGE_VERSION: "7.4"

Deployer 7.4 Node 14:
  <<: *build
  only:
    - main
  variables:
    IMAGE_VERSION: "7.4-node14"

Deployer 8.0:
  <<: *build
  only:
    - main
  variables:
    IMAGE_VERSION: "8.0"

Deployer 8.1:
  <<: *build
  only:
    - main
  variables:
    IMAGE_VERSION: "8.1"
  after_script:
    - docker tag $NAMESPACE:$IMAGE_TAG $NAMESPACE:latest-alpine
    - docker push $NAMESPACE:latest-alpine
    - docker tag $NAMESPACE:$IMAGE_TAG $NAMESPACE:latest
    - docker push $NAMESPACE:latest
